apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-debug-pv
  namespace: order-self-service
  labels:
    name: app-debug-pv
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume/debug"
