apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-debug-pvc
  namespace: order-self-service
spec:
  volumeName: app-debug-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi