apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: order-self-service
  labels:
    app: app
spec:
  selector:
    matchLabels: 
      app: app
  replicas: 2
  template:
    metadata:
      name: app
      labels:
        app: "app"
    spec:
      containers:
        - name: "app"
          image: "willkazahaya/order-self-service:v2.5"
          ports:
          - containerPort: 8080
          
          resources:
            requests: 
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          startupProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            failureThreshold: 30
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            failureThreshold: 30

          envFrom:
            - configMapRef:
                name: app-configmap-env
            - secretRef:
                name: app-secret