apiVersion: v1
kind: Service
metadata:
  namespace: order-self-service
  name: app-service
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - name: app
      protocol: TCP
      port: 8080