apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
  namespace: order-self-service
  labels:
    name: database-persistent-volume
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume/database"
