apiVersion: v1
kind: Service
metadata:
  namespace: order-self-service
  name: database-service
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - name: postgres
      protocol: TCP
      port: 5432